public enum Zadania {
    DOSTARCZANIE_PACZEK,
    KONTAKT_Z_KLIENTEM,
    SORTOWANIE_PACZEK,
    LADOWANIE_SAMOCHODU,
    ROZWIAZYWANIE_KONFILKTOW,
    PRZYJMOWANIE_NOWYCH_PRACOWNIKOW,
    ODBIERANIE_PACZEK
}
